// gender: the profile's gender
// attracted: who the profile is attracted TO
/*
 FORMATTING NOTES
*/
// any filter (that doesn't get displayed) must be formatted as an ARRAY
// if there's a filter for it, there must be a field there, or "includes" breaks
// links MUST start with http:// or https://

//
// AGE ESTIMATOR
//
// TODO break out the approx age function that's used in both of these

function ageBracket(born) {
  // current year
  let date = new Date().getFullYear()
  // approximate age based on birth year
  let age = date - born

  if (age < 30) {
    return "<30"
  } else if (age > 40) {
    return ">40"
  } else {
    return "30-40"
  }
}

// TODO refactor this using modulo
function ageDisplay(born) {
  // current year
  let date = new Date().getFullYear()
  // approximate age based on birth year
  let age = date - born

  // no minors allowed, no ancients expected
  if (age < 18 || age > 99) {
    return "(this entry is broken, please notify goblin)"
  }

  return `${earlyMidLate(age)} ${decade(age)}`
}

const earlyMidLate = (age) => {
  let secondDigit = age.toString()[1]

  if (secondDigit <= 3) {
    return "early"
  } else if (secondDigit >= 4 && secondDigit <= 6) {
    return "mid"
  } else {
    return "late"
  }
}

const decade = (age) => {
  if (age < 20) {
    return "teens"
  } else {
    // returns the first digit of the listed age
    return age.toString()[0] + "0s"
  }
}

//
// ENTRIES
//

const Profiles = [
  {
    name: "lovetheusers",
    link: "https://twitter.com/lovetheusers",
    gender: ["M"],
    attracted: ["F"],
    ldr: ["unspecified"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    loctype: ["unspecified"],
    location: "North Carolina, USA",
    continent: ["North America"],
  },
  {
    name: "orb",
    link: "http://orbnet.net",
    gender: ["M"],
    attracted: ["F"],
    ldr: ["unspecified"],
    type: ["mono"],
    ageBracket: "unspecified",
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "guilherme",
    link: "https://t.co/aJ0C2FzDBK",
    twitter: "https://twitter.com/_sulfUr0",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Sao Paolo, Brazil",
    continent: ["South America"],
  },
  {
    name: "fractal authenticity",
    link: "https://twitter.com/FractalAuth/status/1449966081490046977",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    notes: "cishet / (mostly) monogamous / long distance is scary but maybe?",
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Colorado, USA",
    continent: ["North America"],
  },
  {
    name: "yatharth",
    link: "https://yatharth.brick.do/thread/yatharth-s-date-me-page-XDn9ywbjyl2L",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    twitter: "https://twitter.com/AskYatharth",
    featuredTweet: "https://twitter.com/AskYatharth/status/1384028089659707406",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Venice (Los Angeles), California, USA",
    continent: ["North America"],
  },
  {
    name: "joshua nelson",
    link: "https://twitter.com/joshuayn514/status/1516414741547294728",
    gender: ["M"],
    attracted: ["F"],
    type: ["poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Austin, Texas, USA",
    continent: ["North America"],
  },
  {
    name: "cris p. wicks",
    link: "https://twitter.com/CrispyWicks",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Chicago, Illinois, USA",
    continent: ["North America"],
  },
  {
    name: "pieratt",
    link: "https://twitter.com/pieratttt",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Boston(ish), Massachusetts, USA",
    continent: ["North America"],
  },
  {
    name: "kumbuchaqueen",
    link: "https://twitter.com/kumbuchaqueen/status/1531790619940560896",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "david kobilnyk",
    link: "https://twitter.com/davidkobilnyk",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "matthew skala",
    link: "https://www.twitch.tv/matthewskala/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "gustavo lacerda",
    link: "https://docs.google.com/document/d/1khmwYjPD7cjIC6ssSdH2pYB9BfGCsKvjbrvZoGThkzc/edit?usp=sharing",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "john ohno",
    link: "https://www.lord-enki.net/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "elli",
    link: "https://timeinsensitive.life/date-me/",
    gender: ["M", "NB"],
    type: ["unspecified"],
    ageBracket: "unspecified",
    attracted: ["unspecified"],
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Massachusetts, USA",
    continent: ["North America"],
  },
  {
    name: "rob hardy",
    link: "https://crtr.link/s/rob",
    twitter: "https://twitter.com/ungatedcreative",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Tucson, Arizona, USA / actively looking for new places to move and put down roots",
    notes: "might be open to short-term long-distance",
    continent: ["North America"],
  },
  {
    name: "zmavli caimle",
    link: "https://twitter.com/zmavli",
    gender: ["M"],
    attracted: ["M"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "wiskerz",
    link: "https://wiskerz.me/date/",
    gender: ["M"],
    type: ["mono"],
    ageBracket: "unspecified",
    attracted: ["F"],
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "south of France",
    continent: ["Europe"],
  },
  {
    name: "neil thawani",
    link: "https://lioninawhat.com/love",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
    notes: "(mostly) interested in women / (mostly) monogamous",
  },
  {
    name: "aella",
    link: "https://docs.google.com/document/d/1ircYicvNaC3-ijI1lMBL0xP5rvSKwlKpXepXO-tbH48/edit?usp=sharing",
    gender: ["F"],
    attracted: ["M"],
    type: ["poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "laura sofia",
    link: "https://twitter.com/owlsarepurple",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    location: "Ivory Coast",
    continent: ["Africa"],
  },
  {
    name: "jewel andraia",
    link: "https://twitter.com/ALadyJewel",
    gender: ["F", "NB"],
    attracted: ["F", "NB", "M"],
    type: ["poly"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["unspecified"],
    notes:
      "if i don't communicate queer trans bi ADHD solo-poly by the end of the first date, i didn't overshare properly",
    location: "Bay Area, California, USA",
    continent: ["North America"],
  },
  {
    name: "patrick farley",
    link: "https://patrickdfarley.com/contact/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "New York City, New York, USA",
    continent: ["North America"],
  },
  {
    name: "brooke",
    link: "https://twitter.com/gptbrooke/status/1677883886364430336?s=20",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageBracket: "unspecified",
    notes:
      "if the right person comes along and they don't check some of those boxes then i will change my boxes",
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "California, USA",
    continent: ["North America"],
  },
  {
    name: "josh mcmichael",
    link: "https://twitter.com/jmcmichael",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageBracket: "unspecified",
    notes:
      "interested in relationship as a container for growth, recovery, companionship, exploration",
    ldr: ["N"],
    loctype: ["unspecified"],
    location: "St. Louis, Missouri, USA",
    continent: ["North America"],
  },
  {
    name: "andrew",
    link: "https://twitter.com/filomusus",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Ann Arbor, Michigan, USA",
    continent: ["North America"],
  },
  {
    name: "bruno",
    link: "https://twitter.com/bruno_wilhelm",
    gender: ["M"],
    attracted: ["F"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1982)}`,
    ageBracket: `${ageBracket(1982)}`,
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Cincinnati, Ohio, USA",
    continent: ["North America"],
  },
  {
    name: "adam axolotl",
    link: "https://twitter.com/calxolotl",
    gender: ["M"],
    attracted: ["F", "NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    notes: "physicist doing AI safety, seeking life partner, can tell you lots more via DM :)",
    location: "San Francisco Bay Area (Berkeley), California, USA",
    continent: ["North America"],
  },
  {
    name: "joyoptimizer",
    link: "https://twitter.com/JoyOptimizer",
    gender: ["F"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["Y"],
    loctype: ["unspecified"],
    continent: ["unspecified"],
  },
  {
    name: "james",
    link: "https://twitter.com/INTPhilosopher",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Minneapolis, Minnesota, USA",
    continent: ["North America"],
    notes: `INTP/ Center left person who loves analyzing the hell out of stuff`,
    location: "Plattsburgh, New York, USA",
    continent: ["North America"],
  },
  {
    name: "ethan",
    link: "https://twitter.com/EthanJKemp",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1997)}`,
    ageBracket: `${ageBracket(1997)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Los Angeles, California, USA / might be moving soon",
    continent: ["North America"],
  },
  {
    name: "chris cassano",
    link: "https://guy.bz/",
    twitter: "https://twitter.com/chriscassano",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "San Francisco, California, USA",
    continent: ["North America"],
    notes: "looking for a partner on the adventure of having kids",
  },
  {
    name: "bhargab",
    link: "https://bhargab.com.np/posts/dating-profile/",
    twitter: "https://twitter.com/bhrg3se",
    insta: "https://www.instagram.com/mehawwwww/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Nepal",
    continent: ["Asia"],
  },
  {
    name: "catern",
    link: "https://twitter.com/zcatern",
    gender: ["M"],
    attracted: ["F", "NB", "M"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    type: ["mono", "poly"],
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New York City, New York, USA",
    continent: ["North America"],
  },
  {
    name: "suru!",
    link: "https://twitter.com/13surur?t=2j8nCUYr8U5DRhWfxsprYQ&s=09",
    gender: ["F"],
    attracted: ["NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Madison, Wisconsin, USA at the moment",
    continent: ["North America"],
  },
  {
    name: "martin",
    link: "https://twitter.com/mkhl",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageBracket: "unspecified",
    ldr: ["unspecified"],
    loctype: ["fixed"],
    location: "Germany",
    continent: ["Europe"],
  },
  {
    name: "sophie",
    link: "https://twitter.com/SyzygyCoiled",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Quebec, Canada",
    continent: ["North America"],
  },
  {
    name: "lex",
    link: "https://twitter.com/doseofzero",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(2001)}`,
    ageBracket: `${ageBracket(2001)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes:
      "open to monogamy and polyamory. long distance is kinda scary but im willing to try it out :) hoping to find a partner i can call both my best friend and lover",
    location: "Quezon City, Philippines",
    continent: ["Asia"],
  },
  {
    name: "harlan",
    link: "https://twitter.com/harlanonym",
    gender: ["F"],
    attracted: ["F", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1997)}`,
    ageBracket: `${ageBracket(1997)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Pittsburgh, Pennsylvania, USA / will probably move back to LA at some point",
    continent: ["North America"],
  },
  {
    name: "dan elton",
    link: "https://www.okcupid.com/profile/delton137",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Boston, Massachusetts, USA",
    continent: ["North America"],
  },
  {
    name: "sadmoonanalog",
    link: "https://twitter.com/sadmoonanalog",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes:
      "avid lifter (🏋️‍♀️), amateur potter (🏺). writer by profession. mid-twenties, swolethicc, & greytribe. may not want kids but still wants to build together.",
    location: "Austin, Texas, USA",
    continent: ["North America"],
  },
  {
    name: "christine",
    link: "https://twitter.com/Lil0qui",
    gender: ["F"],
    attracted: ["NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1982)}`,
    ageBracket: `${ageBracket(1982)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    notes:
      "socialist, atheist, optimistic nihilist, spectrum member. into a wide variety of hobbies and esoterica like anime, video games, synthesizers, astronomy, scifi, programming, Magic, etc. no kids, no marriages, easy going. i lift and get outdoors sometimes.",
    location: "Seattle, Washington, USA",
    continent: ["North America"],
  },
  {
    name: "golgi",
    link: "https://twitter.com/GolgiThePrince",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Detroit, Michigan, USA",
    continent: ["North America"],
  },
  {
    name: "torrel",
    link: "https://twitter.com/dyn_westner",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Germany",
    continent: ["Europe"],
  },
  {
    name: "j.r.",
    link: "https://twitter.com/kazundogohda",
    gender: ["M"],
    attracted: ["NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes: "short term long distance okay; likely heading back to the Bay Area in April 2023",
    location: "New Zealand",
    continent: ["Oceania"],
  },
  {
    name: "alex",
    link: "https://twitter.com/aiactorcritic",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1991)}`,
    ageBracket: `${ageBracket(1991)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "London, UK",
    continent: ["Europe"],
  },
  {
    name: "kaixi",
    link: "https://kaixiyang.com/",
    twitter: "https://twitter.com/kaixiyang_",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes:
      "uhhhh 6 foot at least, and really gorgeous goofy ambitious and genius creative men onlyyyy",
    location: "Bay Area / Los Angeles, California, USA",
    continent: ["North America"],
  },
  {
    name: "renee",
    link: "https://twitter.com/reneesolana",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Chicago, Illinois, USA",
    continent: ["North America"],
  },
  {
    name: "kevin walker",
    link: "https://twitter.com/Reccamn?t=7vJVKqKSLJPOI1Cu-mSXiA&s=09",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes: "INFJ / sad about the past and worried for the future, but just living for tomorrow.",
    location: "San Diego, California, USA",
    continent: ["North America"],
  },
  {
    name: "mercer",
    link: "https://docs.google.com/document/d/1FUcf4P06yVo4bJB0lRYiq_gn-0cE0glo1YNAWO0jz4g/edit?usp=sharing",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1999)}`,
    ageBracket: `${ageBracket(1999)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "New York City, New York, USA",
    continent: ["North America"],
  },
  {
    name: "delen",
    link: "https://twitter.com/dheisman",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1983)}`,
    ageBracket: `${ageBracket(1983)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    notes: "i'm pretty cool",
    location: "Philadelphia, Pennsylvania, USA",
    continent: ["North America"],
  },
  {
    name: "shailja",
    link: "https://twitter.com/shailja_0_",
    gender: ["F", "NB"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(2002)}`,
    ageBracket: `${ageBracket(2002)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Mumbai, India",
    continent: ["Asia"],
  },
  {
    name: "braverius",
    link: "https://twitter.com/braverius",
    gender: ["M"],
    attracted: ["F", "NB", "M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "~Seattle, Washington, USA",
    continent: ["North America"],
  },
  {
    name: "graham bessellieu",
    link: "https://sites.google.com/view/cgbessellieu-dating/home",
    gender: ["NB", "M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Central New Jersey, USA",
    continent: ["North America"],
  },
  {
    name: "chris",
    link: "https://twitter.com/mosephos",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "New York City, New York, USA",
    continent: ["North America"],
  },
  {
    name: "tiger",
    link: "https://twitter.com/kafkamacchiato",
    gender: ["F"],
    attracted: ["F", "NB"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1991)}`,
    ageBracket: `${ageBracket(1991)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    notes: "post-op trans woman who missed out on her teenage years and now wants to fuck around",
    location: "Gothenburg, Sweden",
    continent: ["Europe"],
  },
  {
    name: "brian",
    link: "https://twitter.com/LagodaBrian",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1992)}`,
    ageBracket: `${ageBracket(1992)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    notes: `i love my (in-person) job, but, one way or another, i imagine i'll be free to move someday.`,
    location: "Metro DC (Northern Virginia), USA",
    continent: ["North America"],
  },
  {
    name: "matthew",
    link: "https://twitter.com/Robin_ChillJams",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes: `into left wing politics (though i am a bit idiosyncratic, see my tweets), lover of music (house/techno/ambient really any kind of electronic music). i tend to be a cynical but optimistic person. open to a lot of things but i am primary looking for a loving monogamous relationship.`,
    location: "East Tennessee, USA",
    continent: ["North America"],
  },
  {
    name: "haarball",
    link: "https://twitter.com/haarball_",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1986)}`,
    ageBracket: `${ageBracket(1986)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Oslo, Norway",
    continent: ["Europe"],
  },
  {
    name: "daniel",
    link: "https://twitter.com/dangmartin1",
    gender: ["M"],
    attracted: ["M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["N"],
    loctype: ["flexible"],
    notes: "physicist in tech, likes lots of things, fun to talk to",
    location: "Oxford, UK",
    continent: ["Europe"],
  },
  {
    name: "sofy",
    link: "https://claritysofy.com/",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    notes:
      "i’m working on a date me doc atm. but in a nutshell i’m looking for a life partner, someone to go on a secular spiritual journey and build an amazing life together filled with love, books and mutual growth and support",
    location: "Bay Area, California, USA",
    continent: ["North America"],
  },
  {
    name: "observer of suns",
    link: "https://twitter.com/ObserverSuns",
    featuredTweet: "https://twitter.com/ObserverSuns/status/1444757512259915781",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1999)}`,
    ageBracket: `${ageBracket(1999)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    notes: "i’m a graduate student in computer science!",
    location: "US East Coast (DM for details)",
    continent: ["North America"],
  },
  {
    name: "arin",
    link: "https://twitter.com/arin_spanner",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(2000)}`,
    ageBracket: `${ageBracket(2000)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    notes: `transitioning to blockchain developer. / owns every kind of chapstick. / default optimism. / weeeeeeeeeeee`,
    location: "Stanford, California, USA",
    continent: ["North America"],
  },
  {
    name: "jeffrey ladish",
    link: "https://jeffreyladish.com/dateme",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1991)}`,
    ageBracket: `${ageBracket(1991)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "SF Bay Area, California, USA",
    continent: ["North America"],
  },
  {
    name: "catherio",
    link: "https://cather.io/dateme",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["N"],
    loctype: ["flexible"],
    location: "Berkeley, California, USA",
    continent: ["North America"],
  },
  {
    name: "tiffinWA",
    email: "tell325 AT wgu DOT edu",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1980)}`,
    ageBracket: `${ageBracket(1980)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Washington state, USA",
    continent: ["North America"],
  },
  {
    name: "naia",
    link: "https://twitter.com/nbouscal",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: ["London, UK"],
    continent: ["Europe"],
  },
  {
    name: "kayla",
    link: "https://twitter.com/Estimatrix",
    gender: ["F"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1974)}`,
    ageBracket: `${ageBracket(1974)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Red Bank, New Jersey, USA",
    continent: ["North America"],
  },
  {
    name: "btoh",
    link: "https://twitter.com/btohtoh",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "London, UK (but from Singapore)",
    continent: ["Europe"],
  },
  {
    name: "johnson",
    link: "https://twitter.com/justavagrant_",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Seattle, Washington, USA / France / unknown",
    continent: ["North America", "Europe"],
  },
  {
    name: "dan k",
    link: "https://twitter.com/Yozarian22",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Austin, Texas, USA",
    continent: ["North America"],
    notes: "regular in the Texas burner community",
  },
  {
    name: "mindfroth",
    link: "https://twitter.com/mindfroth",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1982)}`,
    ageBracket: `${ageBracket(1982)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Portland, Oregon, USA",
    continent: ["North America"],
  },
  {
    name: "shreeda",
    link: "https://cheerful-marmoset-af5.notion.site/Date-Me-09842fd0b938499fbbf82dfb8953e747",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Austin, Texas, USA",
    continent: ["North America"],
  },
  {
    name: "hormeze",
    link: "https://hormeze.com/",
    twitter: "https://twitter.com/hormeze",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Berkeley, California, USA",
    continent: ["North America"],
    notes: "currently not a face account but u can dm me for pics",
  },
  {
    name: "leah prime",
    link: "https://twitter.com/leahprime",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1986)}`,
    ageBracket: `${ageBracket(1986)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New York / Colorado, USA … independent",
    continent: ["North America"],
    notes: "three cats, many books",
  },
  {
    name: "kendric",
    link: "https://twitter.com/kendrictonn",
    gender: ["M"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1982)}`,
    ageBracket: `${ageBracket(1982)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Ohio, USA",
    continent: ["North America"],
  },
  {
    name: "piyush",
    link: "https://piyushahuja.github.io/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Cambridge, UK",
    continent: ["Europe"],
    notes:
      "these are qualities my partners have consistently found in me: kindness, intellligence, gentleness, sincerity, trustworthiness",
  },
  {
    name: "nocturne chic girl",
    link: "https://twitter.com/nocturnechic",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "New York City, New York, USA",
    continent: ["North America"],
  },
  {
    name: "rob",
    link: "https://twitter.com/yungcrichton?s=21&t=j6KIrrSWHbeS-nrzVrFFHw",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Atlanta, Georgia, USA",
    continent: ["North America"],
    notes: "med student who likes movies ",
  },
  {
    name: "simmo",
    link: "https://www.facebook.com/mrsimmosimpson/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1983)}`,
    ageBracket: `${ageBracket(1983)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "nomad seeking a base",
    continent: ["unspecified"],
  },
  {
    name: "norn",
    link: "https://twitter.com/CinnabonGarf",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Barcelona, Spain",
    continent: ["Europe"],
  },
  {
    name: "bryan mock",
    link: "https://twitter.com/bmock?t=geD6Lk2IiRoIkItpXXFSYA&s=09",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1988)}`,
    ageBracket: `${ageBracket(1988)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Cedar Rapids, Iowa, USA",
    continent: ["North America"],
  },
  {
    name: "aaron james munzer",
    link: "https://twitter.com/ajmunz?s=21&t=udwWEHJc0mh7gGygyvhCrA",
    insta: "https://instagram.com/ajmunzz?igshid=YmMyMTA2M2Y=",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1992)}`,
    ageBracket: `${ageBracket(1992)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "St. Louis, Missouri, USA",
    continent: ["North America"],
    notes:
      "Long distance match okay but strongly not preferred. Location is fixed for now but can travel.",
  },
  {
    name: "jordan",
    link: "https://twitter.com/WickJordan",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1996)}`,
    ageBracket: `${ageBracket(1996)}`,
    ldr: ["N"],
    loctype: ["flexible"],
    location: "San Francisco, California, USA",
    continent: ["North America"],
    notes: "will potentially go to NYC",
  },
  {
    name: "lin",
    link: "https://twitter.com/Linialomdil",
    gender: ["F", "NB"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1997)}`,
    ageBracket: `${ageBracket(1997)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Triangle area, North Carolina, USA",
    continent: ["North America"],
    notes:
      "looking for a long term relationship if possible. Not very experienced in dating, but I make really good spaghetti",
  },
  {
    name: "eris",
    link: "https://twitter.com/spookylinetime",
    gender: ["F"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Boston, Massachusetts, USA",
    continent: ["North America"],
    notes: "You probably don’t like me but here goes.",
  },
  {
    name: "ein",
    link: "https://twitter.com/aria_ein",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(2000)}`,
    ageBracket: `${ageBracket(2000)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Vancouver, BC, Canada",
    continent: ["North America"],
  },
  {
    name: "hermes",
    link: "https://twitter.com/Hermes2110",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "North Texas near the Denton area, USA",
    continent: ["North America"],
    notes:
      "im a pagan and fairly religious and interested in woo, so my match needs to be atleast open to this.",
  },
  {
    name: "lulie",
    link: "https://www.lulie.co.uk/date-me/",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Oxford, UK",
    continent: ["Europe"],
  },
  {
    name: "varun",
    link: "https://linktr.ee/kladhest",
    gender: ["M"],
    attracted: ["F", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Bangalore, India",
    continent: ["Asia"],
  },
  {
    name: "paul e",
    link: "mailto:pecheverri@protonmail.com",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1974)}`,
    ageBracket: `${ageBracket(1974)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "San Jose, California, USA",
    continent: ["North America"],
  },
  {
    name: "mati roy",
    link: "https://matiroy.com/writings/My-dating-profile.html",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "North America",
    continent: ["North America"],
  },
  {
    name: "tim",
    link: "https://twitter.com/indictsGW?t=Nnbrxf87c9jO5VtWzErfnw&s=09",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1984)}`,
    ageBracket: `${ageBracket(1984)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Florida, USA",
    continent: ["North America"],
    notes: "On Fetlife. Non-vanilla sub/switch, open to F/m or M/f Lifestyle bdsm.",
  },
  {
    name: "purpskurp",
    link: "https://twitter.com/purpleskurp",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1997)}`,
    ageBracket: `${ageBracket(1997)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Ohio, USA",
    continent: ["North America"],
    notes: "Please only contact if you have been invited to beautiful princess island",
  },
  {
    name: "frances kafka",
    link: "https://twitter.com/pachabelcanon",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(2002)}`,
    ageBracket: `${ageBracket(2002)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Singapore",
    continent: ["Asia"],
  },
  {
    name: "michael moody",
    link: "https://www.twitter.com/siahsargus",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "São Paulo, Brazil / Texas, USA / Singapore",
    continent: ["South America", "North America", "Asia"],
  },
  {
    name: "kenzie",
    link: "https://www.twitter.com/kenzierecords",
    gender: ["F"],
    attracted: ["F", "M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1992)}`,
    ageBracket: `${ageBracket(1992)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "San Diego, California, USA",
    continent: ["North America"],
    notes: "",
  },
  {
    name: "zev",
    link: "https://twitter.com/strangers_gate",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1985)}`,
    ageBracket: `${ageBracket(1985)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "nomad in the US",
    continent: ["North America"],
    notes:
      "seeking a partner to: build a beautiful life together; enjoy the blood, sweat, and tears together; seek awakening together; go further together",
  },
  {
    name: "will newsome",
    link: "https://twitter.com/willdoingthings",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1991)}`,
    ageBracket: `${ageBracket(1991)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Berkeley, California, USA",
    continent: ["North America"],
    notes: "into Jewish size queens who listen to post-punk",
  },
  {
    name: "talishabot",
    link: "https://twitter.com/TalishaBot",
    gender: ["F"],
    attracted: ["F"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["unspecified"],
    location: "Phoenix, Arizona, USA",
    continent: ["North America"],
  },
  {
    name: "celeste",
    link: "https://celeste.exposed",
    gender: ["NB"],
    attracted: ["F", "NB", "M"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(2004)}`,
    ageBracket: `${ageBracket(2004)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "location: ???",
    continent: ["unspecified"],
  },
  {
    name: "big friendly kiwi",
    link: "https://twitter.com/increase_la",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Vancouver, BC, Canada",
    continent: ["North America"],
  },
  {
    name: "paul",
    link: "https://twitter.com/raver1975",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1975)}`,
    ageBracket: `${ageBracket(1975)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New London, Wisconsin, USA",
    continent: ["North America"],
    notes: `Windsurfer, Kiteboarder, Wingskater, Mathematician, Christian,`,
  },
  {
    name: "aveline",
    link: "https://twitter.com/yinvara",
    gender: ["F"],
    attracted: ["F", "NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(2001)}`,
    ageBracket: `${ageBracket(2001)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "San Diego, California, USA",
    continent: ["North America"],
    notes: `a little shy`,
  },
  {
    name: "C.D.N.",
    link: "https://twitter.com/nephew_jonathan",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["N"],
    loctype: ["flexible"],
    location: "Washington, DC, USA",
    continent: ["North America"],
    notes: `Latin teacher, but probably capable of doing many things; somewhat willing to travel for the right person. Would like children.`,
  },
  {
    name: "andalib",
    link: "https://linktr.ee/andalib33",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Atlanta, Georgia, USA",
    continent: ["North America"],
  },
  {
    name: "ken",
    link: "https://twitter.com/woolbeigecardi",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Ottowa, Ontario, Canada",
    continent: ["North America"],
  },
  {
    name: "drew schorno",
    link: "https://paper.dropbox.com/doc/Drew-Schorno-Dating-Profile--Bz5WzQNF~sGTYvwVk1paNJDIAQ-amNKJuShTKeuFNackmmCE",
    gender: ["M"],
    attracted: ["F", "NB", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1989)}`,
    ageBracket: `${ageBracket(1989)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Victoria, BC, Canada",
    continent: ["North America"],
  },
  {
    name: "wes",
    link: "https://docs.google.com/document/d/1w2jH3CRis1b8G8yuBEZnXLIc-wWCbpc_jr-rYOvcHvU/edit",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1983)}`,
    ageBracket: `${ageBracket(1983)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Collingswood, New Jersey, USA",
    continent: ["North America"],
    notes: `Philadelphia area, married & poly with small child, looking for people who want to hang out, come to my parties/board game meetups, and maybe kiss once in a while. Planning on attending Vibecamp 2023`
  },
  {
    name: "eneasz",
    link: "https://docs.google.com/document/d/1hK38_fYfwm8wxs4avMFXuuP1jf5FwjlJe7yrZHnPeAE/edit?usp=sharing",
    email: "embrodski AT gmail DOT com",
    gender: ["M"],
    attracted: ["F"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1980)}`,
    ageBracket: `${ageBracket(1980)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Denver, Colorado, USA",
    continent: ["North America"],
    notes: `Friendly, Poly, Goth & Dance plz`
  },
  {
    name: "alec",
    link: "https://twitter.com/anti_stokes",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New Jersey, USA",
    continent: ["North America"],
    notes: `graduate student, maybe moving in 6 months(to ?) [editor's note: as of March 20, 2023]`
  },
  {
    name: "tyler alterman",
    link: "https://tyleralterman.com/Tyler-is-looking-for-his-lady-4ff34119d4f1412eb7f1cbd75c33ccbc",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly", "unspecified"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "New York City, New York, USA",
    continent: ["North America"],
    notes: `monogam-ish. What I’m looking for: First take: a partner-in-crime to raise kids with. Second take: I am open to __________ (as a general way of life). `
  },
  {
    name: "kanishk arora",
    link: "https://twitter.com/yoyo_galactic",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1998)}`,
    ageBracket: `${ageBracket(1998)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New Delhi, India",
    continent: ["India"],
    notes: `I am chemical engineer working in IOT Field from India . Want to find smart people.`
  },
  {
    name: "caleb",
    link: "https://docs.google.com/document/d/1nXcBa-tf5bTE-Do24DrwoJH3csD1LJGC55zM2HIKdF4/edit?usp=sharing",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1995)}`,
    ageBracket: `${ageBracket(1995)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Washington, DC",
    continent: ["North America"],
  },
  {
    name: "bzanderson",
    link: "https://twitter.com/Beatriz20427952",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(2000)}`,
    ageBracket: `${ageBracket(2000)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "near Pittsburgh, Pennsylvania, USA",
    continent: ["North America"],
    notes: `Recent uni graduate, autistic, looking for women in same age range with long hair and a non-mothering but empathetic personality`
  },
  {
    name: "sanje",
    link: "https://twitter.com/sanjehorah?s=21",
    gender: ["F"],
    attracted: ["F", "M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(2001)}`,
    ageBracket: `${ageBracket(2001)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Singapore",
    continent: ["Asia"],
  },
  {
    name: "box",
    link: "https://twitter.com/untiltrees",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1993)}`,
    ageBracket: `${ageBracket(1993)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Paris, France",
    continent: ["Europe"],
  },
  {
    name: "flower",
    link: "https://twitter.com/FlowerMage424",
    gender: ["M"],
    attracted: ["F"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1987)}`,
    ageBracket: `${ageBracket(1987)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Southern New Hampshire, USA",
    continent: ["North America"],
    notes: `in all seriousness, AMA`
  },
  {
    name: "maryzoso",
    link: "https://twitter.com/MaryZoso",
    gender: ["F"],
    attracted: ["NB", "M"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1980)}`,
    ageBracket: `${ageBracket(1980)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Indianapolis, Indiana, USA",
    continent: ["North America"],
  },
  {
    name: "phaent",
    link: "https://twitter.com/PhaentGames",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1986)}`,
    ageBracket: `${ageBracket(1986)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "DFW, Texas, USA",
    continent: ["North America"],
    notes: `I travel for work a fair bit, and may be near you more often than it seems!`
  },
  {
    name: "dan hoffman",
    link: "https://thedanhoffman.github.io/",
    twitter: "https://twitter.com/thedanhoffman",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1999)}`,
    ageBracket: `${ageBracket(1999)}`,
    ldr: ["N"],
    loctype: ["fixed"],
    location: "Portland, Oregon, USA",
    continent: ["North America"],
    notes: `recreational math stuff, book worm (mostly obscure non-fiction), computer whiz bang, twitter is private but feel free to DM`
  },
  {
    name: "lauren e",
    link: "https://twitter.com/LaurenE_UX",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1983)}`,
    ageBracket: `${ageBracket(1983)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Salt Lake City, Utah, USA",
    continent: ["North America"],
    notes: `I’m open to friends and mates!`
  },
  {
    name: "keller",
    link: "https://docs.google.com/document/d/1J83RuVzfrtNPGnARwOeisi5es77CeUApSpM3efazHfw/edit?usp=drivesdk",
    gender: ["M"],
    attracted: ["F", "NB", "M"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Washington, DC, USA",
    continent: ["North America"],
  },
  {
    name: "neall",
    link: "https://neall.org/",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "San Francisco, California, USA",
    continent: ["North America"],
  },
  {
    name: "jose j",
    link: "https://twitter.com/lizardinspring",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1994)}`,
    ageBracket: `${ageBracket(1994)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Valladolid & Salamanca (Spain)",
    continent: ["Europe"],
    notes: `I'm an spanish guy interested in building creative endeavours in literature and philosophy`
  },
  {
    name: "alexandra 💗",
    twitter: "https://twitter.com/innerpathing",
    link: "https://alexandraheller.substack.com",
    link: "https://alexandraheller.com",
    gender: ["F"],
    attracted: ["M"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1985)}`,
    ageBracket: `${ageBracket(1985)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "nomadic",
    continent: ["unspecified"],
    notes: `into buddhism, psychedelics, helping the world, wholesomeness, etc :) `
  },
  {
    name: "mission-junkie",
    link: "https://www.notion.so/pareen-444d5977494a423ab61732f9bf861691?pvs=4",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1986)}`,
    ageBracket: `${ageBracket(1986)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "India",
    continent: ["Asia"],
    notes: `Old school. Ambitious. Collectivist. Not “exploring”. Want someone solid.`
  },
  {
    name: "autistic jewish edgelord person",
    gender: ["M"],
    attracted: ["F"],
    type: ["mono"],
    ageDisplay: `${ageDisplay(1996)}`,
    ageBracket: `${ageBracket(1996)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "New York City, New York, USA",
    continent: ["North America"],
    notes: `i like cartoons, musical theater, and niche internet politics. my discord is notoriousp_i_g.`
  },
  {
    name: "protoneutype",
    link: "https://twitter.com/protoneutype",
    gender: ["M"],
    attracted: ["F", "NB"],
    type: ["mono", "poly"],
    ageDisplay: `${ageDisplay(1990)}`,
    ageBracket: `${ageBracket(1990)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "mid-sized university town in midwest, USA",
    continent: ["North America"],
    notes: `pansexual who's dated men and is curious about women`
  },
  {
    name: "bollu",
    email: "siddu.druid AT gmail DOT com ",
    gender: ["NB"],
    attracted: ["F", "NB"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1996)}`,
    ageBracket: `${ageBracket(1996)}`,
    ldr: ["Y"],
    loctype: ["flexible"],
    location: "Edinburgh, UK",
    continent: ["Europe"],
    notes: `fuck around and find out :)`
  },
  {
    name: "tipsy",
    link: "https://twitter.com/tipsycaek",
    gender: ["F"],
    attracted: ["M"],
    type: ["poly"],
    ageDisplay: `${ageDisplay(1991)}`,
    ageBracket: `${ageBracket(1991)}`,
    ldr: ["Y"],
    loctype: ["fixed"],
    location: "Los Angeles, California, USA",
    continent: ["North America"],
    notes: `perpetually touch-starved, incessantly attention-seeking. generally into bigger dudes (soft and/or strong). subby, weeaboo, internet-poisoned, low-agency, not-actually-poly-just-slutty. slimegirl. let me smell you.`
  },

  // FORMAT TO PASTE
  // {
  //   name: "",
  //   link: "",
  //   gender: [""],
  //   attracted: [""],
  //   type: [""],
  //   ageDisplay: `${ageDisplay()}`,
  //   ageBracket: `${ageBracket()}`,
  //   ldr: [""],
  //   loctype: [""],
  //   location: "",
  //   continent: [""],
  //   notes: ``
  // },

  // WAITING
   // ~#64 vincent - add if confirms
  // ~#105 phaent - add if confirms

  // if location filter breaks it's probably bc you forogt to add "loctype: ['unspecified']" to a profile

  // IDEAS
  // tipsy: "a slightly more standardized location input might make filtering better (searching the page for many variations of how one might refer to an area is a bit of a drag, esp since most ppl use 2-letter states which aren't v cmd-f'able considering pairs of letters often show up within words)""
  // color code newest entries?
  // distinguish "date me profile" from twitter account, insta, email...
  // mention if bounty (and amount)
  // clear options, select multiple

  // SUGGESTIONS
  // brian: "I thought the sentence-based interface was less confusing than the new one that just has gender lists in two places."
  // @zcatern: "show me a random person and open their DMs" or something button, to motivate interactions
  // lin/@linialomdil: Would be nice to be able to select multiple options at once in some of the finer categories (like gender or attracted to), but it's not a big deal due to the small number of entries I think
]

export default Profiles
